### ISSUE TITLE
Forks, Clones, PR's... Oh my!

### ISSUE THREAD

**Issue by MikeSiLVO** [MikeSiLVO/skin.aeon.madnox#29]
@MadMikeDoc I got your PM on the Kodi forum but thought it best to respond here in case @bartolomesoriano or @meowmoo have similar issues.

You don't need to fork my fork cause since my fork is a fork of your repository it is sort of already forked.

Whatever you do don't say fork it! 😜 

I think for ease of use we should all use SmartGit. After install click on or clone https://github.com/MadMikeDoc/skin.aeon.madnox if not done so already. After checkout go to the top menu Remote > Add then enter https://github.com/mikesilvo164/skin.aeon.madnox. After it is added you should see it in the branches view. Right click and choose Pull > Fetch. ONce it is finished you will see the leia and krypton branches. Double click the leia branch and name it whatever youd like that is different from leia. You now should have my fork as your checkout branch. We can worry about the PR stuff after we get you checkout out on the right branch. Typing this quickly so please comment or ask any questions if I missed something... 👍

**Comment by bartolomesoriano** [comment]
Thanks @mikesilvo164, I just started using SmartGit.  I will try having your fork as my checkout branch tonight.

**Comment by mikesilvo164** [comment]
@bartolomesoriano I don't get a notification if you edit. I actually prefer to use the GitHub website to do all my PR stuff. I use SmartGit for managing the commits and branches.

**Comment by bartolomesoriano** [comment]
@mikesilvo164, my apologies, I did not know there were no notifications on edits.  So then, should I fork your repo in the GitHub site, upload my commits and PR from there?

**Comment by mikesilvo164** [comment]
@bartolomesoriano Never any need to apologize buddy 😃 

I do not think you can fork cause you already forked MadMikeDoc MadNox. You would need to follow the instructions posted at the top of this issue and then push the branch to your forked repo then you can make a PR by choosing my branch from the options. If there are any issues at all just post again and we can take it step by step whenever you have time 👍

**Comment by mikesilvo164** [comment]
@bartolomesoriano I am mistaken with my terminology you do not want to clone you want to add the repo and not clone. Please let me know if you have any issues 👍
